name: built_graphql_client_generator
description: Provides a simple generated visitor pattern based solution for creating a graphql client.
version: 1.0.0
author: Guy Peled <guypeled76@gmail.com>
homepage: https://github.com/guypeled76/built_graphql_client

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  build: '>=0.12.0 <2.0.0'
  petitparser: ^2.4.0
  source_gen: ^0.9.0
  built_graphql_client:
    path: ../built_graphql_client/
  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0