name: built_graphql_client
description: Provides a simple generated visitor pattern based solution for creating a graphql client.
version: 1.0.0
author: Guy Peled <guypeled76@gmail.com>
homepage: https://github.com/guypeled76/built_graphql_client

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:

dev_dependencies:
  test: 1.3.4